### ISSUE TITLE
[Issue: Question]: i use default helm deploy in k8s cluster but the grafana don't have data

### ISSUE THREAD

**Issue by wnz27** [groundcover-com/caretta#44]
<img width="1317" alt="截屏2023-01-18 21 57 25" src="https://user-images.githubusercontent.com/12094918/213190084-
7871e15e-c5bc-4458-ac3c-add8fd2d1f2e.png">

i dont why

**Comment by wnz27** [comment]
<img width="1298" alt="截屏2023-01-18 22 00 42" src="https://user-images.githubusercontent.com/12094918/213190886-e0c9dbaf-5cd3-412c-ba50-2e0100fc213b.png">

**Comment by udiz** [comment]
Hey, can you share the logs of the Caretta pods?
You can use `kubectl logs -l app=caretta -n caretta`

**Comment by frabe1579** [comment]
Me too.
This is the log, almost identical in all nodes:
```
2023/01/18 17:47:08 Error retreiving owner of kps-grafana-5f9549d9bb - Missing replicaset for UID 52c9acf0-5d47-4e05-97ac-16414fd0746d
2023/01/18 17:47:08 Error retreiving owner of kps-kube-prometheus-stack-prometheus - Unsupported kind for lookup - Prometheus
2023/01/18 17:47:08 Error retreiving owner of login-5cfb56bf99 - Missing replicaset for UID 9618f538-8370-4893-b958-740bb9683dad
2023/01/18 17:47:09 Error retreiving owner of pg0 - Unsupported kind for lookup - Cluster
2023/01/18 17:47:09 Error retreiving owner of kps-kube-prometheus-stack-prometheus - Unsupported kind for lookup - Prometheus
2023/01/18 17:47:09 Error retreiving owner of kps-kube-prometheus-stack-alertmanager - Unsupported kind for lookup - Alertmanager
2023/01/18 17:47:09 Error retreiving owner of pg0 - Unsupported kind for lookup - Cluster
2023/01/18 17:47:09 Error retreiving owner of pg0 - Unsupported kind for lookup - Cluster
2023/01/18 17:47:09 Error retreiving owner of pg0 - Unsupported kind for lookup - Cluster
2023/01/18 17:47:20 Couldn't load probes - error loading BPF objects from go-side. field HandleSockSetState: program handle_sock_set_state: map .rodata: map create: read- and write-only maps not supported (requires >= v5.2)
```
Kubernetes on OVH, version 1.23.14

**Comment by udiz** [comment]
Hey @frabe1579, I tagged a new release today that might fix your issue. You can try again, remember to update the Helm repository.

**Comment by frabe1579** [comment]
I think the problem is now resolved, but I have a new error, related to the kernel version 4.15, but the requirement is 4.16:
```
2023/01/19 13:42:39 Couldn't load probes - error loading BPF objects from go-side. field HandleSockSetState: program handle_sock_set_state: apply CO-RE relocations: no BTF found for kernel version 4.15.0-200-generic: not supported
```
Can you confirm the error is only due to the requirement of 4.16 kernel?

**Comment by udiz** [comment]
This error message is due to lack of CO-RE support in the linux version you're running, as mentioned here - https://github.com/groundcover-com/caretta#requirements . It doesn't depend solely on the kernel version, but this kernel version can't support CO-RE.

**Comment by wnz27** [comment]
> https://github.com/groundcover-com/caretta#requirements

ok， i try it latter

**Comment by wnz27** [comment]
<img width="905" alt="截屏2023-01-20 08 27 57" src="https://user-images.githubusercontent.com/12094918/213592129-d5d5d83d-3328-427e-a3e4-2c44deb8bccf.png">

i try it, and the log is this.

still dont have data

**Comment by avivzgroundcover** [comment]
As stated in the comment by @udiz above - the issue with both installations is the lack of CO:RE information in the machine. The README file describes which linux distributions added support and starting on what version. I'm closing this issue as it is not something we can deal with, but rather a requirement of the system.
